# These are supported funding model platforms

custom: ['https://www.buymeacoffee.com/vitim']
ko_fi: victornpb
github: victornpb
patreon: # Replace with a single Patreon victornpb
open_collective: # Replace with a single Open Collective victornpb
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay victornpb
issuehunt: # Replace with a single IssueHunt victornpb
otechie: # Replace with a single Otechie victornpb
